# Generated by Django 4.2.13 on 2024-08-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candles',
            new_name='Candle',
        ),
        migrations.RenameModel(
            old_name='Gift_Cards',
            new_name='Gift_Card',
        ),
    ]
