# Generated by Django 4.2.13 on 2024-08-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rename_candles_candle_rename_gift_cards_gift_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essential_oil',
            old_name='cultivation_method',
            new_name='extraction_method',
        ),
        migrations.RemoveField(
            model_name='essential_oil',
            name='extraction_process',
        ),
    ]
