# Generated by Django 4.2.13 on 2024-08-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_rename_cultivation_method_essential_oil_extraction_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_oil',
            name='plant_part',
            field=models.CharField(default='flower', max_length=255),
        ),
    ]
