# Generated by Django 4.2.13 on 2024-08-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_essential_oil_plant_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='capacity',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='candle',
            name='color',
            field=models.CharField(default='white', max_length=255),
        ),
        migrations.CreateModel(
            name='Difussor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specifications', models.CharField(max_length=255)),
                ('features', models.CharField(max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewer.product')),
            ],
        ),
    ]
