# Generated by Django 4.2.13 on 2024-08-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_candle_capacity_candle_color_difussor'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_oil',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
