# Generated by Django 4.2.13 on 2024-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_essential_oil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential_oil',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
