# Generated by Django 4.2.13 on 2024-08-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_remove_essential_oil_image_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='essential_oil',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
