# Generated by Django 4.2.13 on 2024-08-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_remove_product_image_essential_oil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
