# Generated by Django 4.2.13 on 2024-08-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_candle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='difussor',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gift_card',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
