# Generated by Django 4.2.13 on 2024-08-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_remove_candle_image_remove_difussor_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Difussor',
            new_name='Diffusor',
        ),
    ]
