# Generated by Django 4.2.13 on 2024-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_rename_difussor_diffusor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
